# Generated by Django 6.0.7 on 2026-09-14 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_google_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('PRIVACY', 'Privacy Policy'), ('TERMS', 'Terms of Use')], max_length=20)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], default='DRAFT', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-status', 'policy_type', '-version'),
                'constraints': [models.UniqueConstraint(fields=('policy_type', 'version'), name='unique_policy_type_version')],
            },
        ),
        migrations.CreateModel(
            name='PolicyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='core.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('policy__policy_type',),
                'constraints': [models.UniqueConstraint(fields=('user', 'policy'), name='unique_user_policy_consent')],
            },
        ),
    ]
