# Generated by Django 6.0.7 on 2026-09-15 01:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_initial_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookiePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essential_cookies_accepted', models.BooleanField(default=True)),
                ('optional_cookies', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='policyconsent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='policyconsent',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REVOKED', 'Revoked')], default='ACCEPTED', max_length=20),
        ),
        migrations.AddField(
            model_name='policyconsent',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='policyconsent',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('PRIVACY', 'Privacy Policy'), ('TERMS', 'Terms of Use'), ('COOKIE', 'Cookie Policy'), ('AIRA', 'AIRA / AI Data-Use Notice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='policyconsent',
            name='accepted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='policyconsent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('ACCEPTED', 'REVOKED'))), name='policyconsent_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='policyconsent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVOKED'), ('withdrawn_at__isnull', False)), models.Q(('status', 'ACCEPTED'), ('withdrawn_at__isnull', True)), _connector='OR'), name='policyconsent_withdrawal_timestamp'),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cookie_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cookiepreference',
            constraint=models.CheckConstraint(condition=models.Q(('essential_cookies_accepted', True)), name='cookiepreference_essential_always_active'),
        ),
    ]
