# Generated by Django 6.0.7 on 2026-08-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0003_evidencerequirement_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAssignment',
            fields=[
                (
                    'id',
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('deadline', models.DateField()),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'area',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assignments',
                        to='accreditation.accreditationarea',
                    ),
                ),
                (
                    'assigned_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='created_area_assignments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='accreditation_area_assignments',
                        to='core.department',
                    ),
                ),
            ],
            options={
                'ordering': ('deadline', 'department__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='areaassignment',
            constraint=models.UniqueConstraint(
                fields=('area', 'department'),
                name='unique_area_assignment_department',
            ),
        ),
    ]
