# Generated by Django 6.0.7 on 2026-08-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0005_alter_areaassignment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencereview',
            name='decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REQUEST_REVISION', 'Request Revision'), ('COMPLIED', 'Complied'), ('NON_COMPLIED', 'Non-Complied'), ('CLOSED', 'Complied')], max_length=30),
        ),
        migrations.AlterField(
            model_name='evidencereview',
            name='from_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_DEAN_REVIEW', 'Under Dean Review'), ('UNDER_AREA_CHAIR_REVIEW', 'Under Area Chair Review'), ('UNDER_QA_REVIEW', 'Under QA Review'), ('NEEDS_REVISION', 'Needs Revision'), ('COMPLIED', 'Complied'), ('NON_COMPLIED', 'Non-Complied'), ('CLOSED', 'Complied')], max_length=35),
        ),
        migrations.AlterField(
            model_name='evidencereview',
            name='to_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_DEAN_REVIEW', 'Under Dean Review'), ('UNDER_AREA_CHAIR_REVIEW', 'Under Area Chair Review'), ('UNDER_QA_REVIEW', 'Under QA Review'), ('NEEDS_REVISION', 'Needs Revision'), ('COMPLIED', 'Complied'), ('NON_COMPLIED', 'Non-Complied'), ('CLOSED', 'Complied')], max_length=35),
        ),
        migrations.AlterField(
            model_name='evidencesubmission',
            name='revision_return_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_DEAN_REVIEW', 'Under Dean Review'), ('UNDER_AREA_CHAIR_REVIEW', 'Under Area Chair Review'), ('UNDER_QA_REVIEW', 'Under QA Review'), ('NEEDS_REVISION', 'Needs Revision'), ('COMPLIED', 'Complied'), ('NON_COMPLIED', 'Non-Complied'), ('CLOSED', 'Complied')], max_length=35),
        ),
        migrations.AlterField(
            model_name='evidencesubmission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_DEAN_REVIEW', 'Under Dean Review'), ('UNDER_AREA_CHAIR_REVIEW', 'Under Area Chair Review'), ('UNDER_QA_REVIEW', 'Under QA Review'), ('NEEDS_REVISION', 'Needs Revision'), ('COMPLIED', 'Complied'), ('NON_COMPLIED', 'Non-Complied'), ('CLOSED', 'Complied')], default='DRAFT', max_length=35),
        ),
    ]
